[tool.poetry]
name = "shopkeeper"
version = "0.0.0"
description = "Simple example of Pulumi components with Poetry and Pytest"
authors = ["Jake Bouma"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
pulumi = "^3.167.0"
pulumi-aws = "^6.79.2"
boto3 = "^1.38.8"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3"
debugpy = "^1.8.14"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-ra -p no:warnings"
filterwarnings = [
    "ignore::DeprecationWarning:aws.*:"
]
testpaths = [
    "tests", "unit_tests", "integration_tests"
]

[tool.ruff.lint.pycodestyle]
max-doc-length = 88
max-line-length = 100