[tool.poetry]
name = "shopkeeper"
version = "0.0.0"
description = "Simple example of Pulumi components with Poetry and Pytest"
authors = ["Jake Bouma"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
pulumi = "^3.163.0"
pulumi-aws = "^6.0.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3"
black = "^25.1.0"
autopep8 = "^2.3.2"
flake8 = "^7.1.2"
debugpy = "^1.8.14"
pytest-timeout = "^2.3.1"
isort = "^6.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q -p no:warnings"
filterwarnings = [
    "ignore::DeprecationWarning:aws.*:"
]
testpaths = [
    "tests"
]
